# -*- coding: utf-8 -*-
"""simple_linear_regression_on_salary_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jCjUSLN_qO9l57ltrB01jG3mPaWn2xpB

#🌸 Forouzan Fallah 🌸

Github: Forouzanfallah1

Personal Website: Forouzanfallah.ir

Don't hesitate to contact me for any further questions ☺

# Simple Linear Regression

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the **dataset**"""

dataset = pd.read_csv('Salary_Data.csv')

"""##Separate the features and label"""

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

"""## Training the Simple Linear Regression model on the Training set"""

from sklearn.linear_model import LinearRegression
linear_regressor = LinearRegression()
linear_regressor.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_predict = linear_regressor.predict(X_test)

"""## Visualising the Training set results"""

plt.scatter(X_train, y_train, color = 'magenta')
plt.plot(X_train, linear_regressor.predict(X_train), color = 'cyan')
plt.title('Salary based on Experience on Training dataset')
plt.ylabel('Salary')
plt.xlabel('Years of Experience')
plt.show()

"""## Visualising the Test set results"""

plt.scatter(X_test, y_test, color = 'magenta')
plt.plot(X_train, linear_regressor.predict(X_train), color = 'cyan')
plt.title('Salary based on Experience on Test dataset')
plt.ylabel('Salary')
plt.xlabel('Years of Experience')
plt.show()